language: java

env:
  global:
    - secure: "PmlGI87ZrZYx8XKbhKPAoFxL9qgAbn6uXH+sMRFf0Z/Z+v/HZWBhNQk2OekesdIR1FLVDZy5rmnSbl5hKD+2ZOtrNjIgLnnIU73UB2zj1YHs67wKTNtm01FRdRwAOOMgroQeprMr5JcvLEGgChCnTNc1h6zlObsEBXa0F0662u6mP63Flk0RG6XqFvHOG8ArMevND0ssu6iGfXiY4qXKXls26ppLnTcTG3HqssFOp5czV+QUTWEX/VlTkRcqIksmEOOO7FE1bifrzphEEPgsFjN1pLQPHzfWWJCOAXPnQcHonBfzvSeUG/EENzIgQt2JhPBn6E1HN3G8Qpxrmx0+kUQqIEwAzFuviV1CyTcvpC+EIpw8WCVCfEWeGuDa7FaOLkzoWXOapldVVzi9ef+lJSMFOcvRc3nZzRecq53IOAdCXmwxPp0tqiemhhVWWfFxdd5JxwqixALoX2b6wIH9A7pRVyFZaGaILQc2pEbxaLX8xPIPHkco2/eAIDqxsbVv320PLcJGOLktx63I4nCaX60OhZWLrcFFcQFUKI/aI5JYp4pLiLMOZsKuZgOFLPgdlES59xu6aChmieJXcF5gDVFz5D4UdtEz+lJmu9XZk335rNEiqGVeZAP899fd/NsAngLRRQLdFQnIJqrlbrbL31KTqlMa35wDF5kpMFAShgI="
    - secure: "xhcOIopnUPGJJsZ7diclOILtnFWqt/C+j3rfpeDe7bIYSL29FedkelM4d8C1XjoFcAD87maQdQYjoY4p58ilz4Tejhxt7wOq7NT5D4Zz3HsvOfDHAySoavTLuYwD2NPu56DaBUoxn+l9QhDuOuyYrAjlnqgl3/wN3L4VOcxOuLM6n6q8APyTOWOOKkXb81YJM3EbUDPvdfxzdM2/eCn+95EoW+QCYH2jC2dC5HuxcB0MZpTY8jpWMkL+AACEFkaH6b3B5jCXGhlvg5vBx3OkbneVOAoW1IiTarf/S9Q8d6CctLrtkh+1DhWub494eq2LS89mKXzlkzHFAX8ERWQxLtRwz+s1m7yKDnjmbllZftZNfNlKVgzut37cyzPm+vlW+zeMJ4Tdw02zbEucMXlTUAhDr/ZZKSRzBXtJknVzyTedNhiYMjC7P1qQItC5VVQ5H6vvSYlNJoU76Ix1WTP3TXboZtYnMDHDNFkSddZYwNUVi/V72YkjnC4AIs+HUSIEev9ArXHAH/cBxTKEeupyESo3ulMfvBnC+Obx1NHaFQnrVO7buBM0QeDo+n/ym6Va5xI3CXCG8UyIR3/Qm3L9brVTxUq/887GIETdZ0mV4LbTD0bUrEtMboGQu2Ze9rLVQD/PGoxqHOuEjSNxjOXCHN8NmNPZsxzHfvEYDusug0c="
    - MAVEN_THREADS=2

jdk:
  - oraclejdk7

before_install:
  - mkdir -p ~/.m2
  - cp settings.xml ~/.m2

install:
  - mvn -B -T $MAVEN_THREADS clean javadoc:jar source:jar site -Dmaven.javadoc.failOnError=false -Dquiet=true

deploy:
  - mvn -B -T $MAVEN_THREADS org.sonatype.plugins:nexus-staging-maven-plugin:deploy -DnexusUrl=https://oss.sonatype.org/content/repositories/snapshots -DserverId=oss-snapshots -DreleaseType=snapshot

after_success:
  - bash ./trigger-dependent-build
