language: java

env:
  global:
    - secure: "ZXFv57r1lzrCjCzhfEhsqzu/mK+0hi9U2bJHwLyEh9dXMJf8HVCghqwTkm1D298/fvehIjt27uOvP8cbdLtb7uOzV9ZeQaNjqHACPjNMSbwxNwgHwoOe3p6sTGGNFI/KDRrqYYYC2GfIz2Rqp5UD+Ejm9E3Yqof5qey307xoZr+jr4Y75FJA6cF6z01fkAYEfQgzvVAsEAPwQsDo7i4opZ2dh4QHomuO+V/c93is7TScj+Yv+WwYQEWGnPelvZhHWlphNxG1CQxja2zKMWYKttlmmUoFO7aMySPr5nTjHdkm4LxQrlBV1redwWQjZgQKvyfxe8n2FQC+2TtEHndmk9gnRdASLDADzPrWaVatngw6/rmPjW6sb9MhqUtsTUxA2UfWDq545G2ZobpBQI1UxItFpi1vZgDhpJSZ+lQfavKq+YwQ7W20vN/1s8wVbFtV8dvts2W66gdvL2a2OUiYP2SzVtWFHJymY11iEvnoKxYfY0pia8yqfV9ohlaL45QsYkTQvxloDheHUJUU9Ag1laiznVwqsaY1h4p1APinjVNa72H9jBqhqg83VK/jeM2pHiynlNOZHvQx4z8aKhC6g2klkv99aoKpo0f+F/SE0NAcebWkK99ANt8lgz3h5Pf675PbWwYdbjc+NczjVxqwS2Pp71EB4AFrPZwcZVwxo9o="
    - secure: "WsB8Wa6MebKzLT/fngsVJeI8zscdwQ8sPwAgviuc3bitGCUvCkoJbbkKYw7zmGp7UxWvxYYlfyNs6AyCkCiZmjg21HndHAIJefp2S8d0GZXGl38q89RjLtOrsvu0KgJQomIqWc7KfGAWh2zqxSBrpGcAYBlYn1PCr67jwYz437Q/37mdOQWaEEE0Jex3rj6EAhAQDh9dqvORp8HMEZzSCDLYnSTnv2SkVhD4iUofSdRKJ/BsF6VyIfiCIfKGavjQb3nF3qmVmO8SUF/bbVXcDSo+uRTHB61D9FuDqBYjWJmcxVoeMesshqYGQ0BLYKDhqDPERYopyett7FfXDNOcrxomjCaPyNdKKLZaWon0F8aPTuUL9nAeJ1FJm2MLt8bEnjCINrpTtvaudOweslGzt1yH5OSTZhEhNFP9RI7HxMGqvx0mhP4WyTMpM1zWl3QyKqfpV+espkquIeFsCyBdxtKciCgemRaUsedWg1PDXB6xGBYyJKWonD3aDGzIQ+2A79aV0EeJm03Xzym9q7ZpmhYO6s6+toGBya5puCWq5HQ92hSvwPQ7Giya/F9RbHKnyEuJmgKPFT1bFST3SnI4Dd76oiXuZfMmrX0KVR4Zjuqu7lwH0v9jD8992wLAsBB8Rohw7oQeotfj4QvWasappuv4CHcPE3+UT3pYjr+mYSA="
    - MAVEN_OPTS="-Xmx128m -Dquiet=true -Dmaven.javadoc.failOnError=false"

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk7

before_install:
  - cp settings.xml $HOME/.m2

install:
  - mvn -e -B -T 4 clean javadoc:jar source:jar install

after_success:
  - mvn -e -B -T 4 -s settings.xml deploy -DaltDeploymentRepository=oss-sonatype::default::https://oss.sonatype.org/content/repositories/snapshots
  - bash ./trigger-dependent-build
