language: java

env:
  global:
    - secure: "CoSwaRCLPhblbblUpXeJqJttds88AEETp7cEvaKuQfKMMbW1emDWCAAvV+NOX/e8CTvRcnrqYF+8A3DmWBw33xUPp8TGpTHXZFzjQoS5JnqtDyeqVlX7yMnuTeVPkHYWzharpY4H8kFF4RsPitlk2tZnkUdLgoJJe+9aYr+0DhMAxTOqRHuBnsKSEcPj/4MOAq8DlhyaGw5zSp/9E6aeF+iwtZ1KQ+A6aUHfWHYfxKNsXiHt+rB1S3cHQOWEBjnXlgH8CgujjdMCZitSqxURAKa5QQzNnFbkMwiN1rU3JAx79Nqm7SXxZz7BgqYpDv6lFzUWog5qiEpqOD72vRs9cZgE3N1hNE/4Tq9teWfp8q2kIza9lKq3U342dE+D1xV+/P0iLsv3hzPy90hb8xoS/47ZWaWKBpoYj8oZOo4rcBDoSyhFrbKwVC1VG++5yoiVbOI7SRZkTI45oud0hoThcidBzn1a23doURhNA5AQ4f4c5KOkcnRxt0YGkprkbUHs0J4fJ9T0pAYkJfHFWbk7A2s8giG6JSP0s4meE+Jw7B9RMjTOmbSuwIp5+sh+FnoVgSwFxN0BBh6dOL9Bn+Dw1dXw3RDI896/3PauIG7HiQf24KW7MVxpXckmS3qyosv+4eCjBnwVrwKrQjdAmZ772yrbABIdcmFMaHDAyxcSxxo="
    - secure: "xhcOIopnUPGJJsZ7diclOILtnFWqt/C+j3rfpeDe7bIYSL29FedkelM4d8C1XjoFcAD87maQdQYjoY4p58ilz4Tejhxt7wOq7NT5D4Zz3HsvOfDHAySoavTLuYwD2NPu56DaBUoxn+l9QhDuOuyYrAjlnqgl3/wN3L4VOcxOuLM6n6q8APyTOWOOKkXb81YJM3EbUDPvdfxzdM2/eCn+95EoW+QCYH2jC2dC5HuxcB0MZpTY8jpWMkL+AACEFkaH6b3B5jCXGhlvg5vBx3OkbneVOAoW1IiTarf/S9Q8d6CctLrtkh+1DhWub494eq2LS89mKXzlkzHFAX8ERWQxLtRwz+s1m7yKDnjmbllZftZNfNlKVgzut37cyzPm+vlW+zeMJ4Tdw02zbEucMXlTUAhDr/ZZKSRzBXtJknVzyTedNhiYMjC7P1qQItC5VVQ5H6vvSYlNJoU76Ix1WTP3TXboZtYnMDHDNFkSddZYwNUVi/V72YkjnC4AIs+HUSIEev9ArXHAH/cBxTKEeupyESo3ulMfvBnC+Obx1NHaFQnrVO7buBM0QeDo+n/ym6Va5xI3CXCG8UyIR3/Qm3L9brVTxUq/887GIETdZ0mV4LbTD0bUrEtMboGQu2Ze9rLVQD/PGoxqHOuEjSNxjOXCHN8NmNPZsxzHfvEYDusug0c="
    - MAVEN_THREADS=2

jdk:
  - oraclejdk7

before_install:
  - mkdir -p ~/.m2
  - cp settings.xml ~/.m2

install:
  - mvn -B -T $MAVEN_THREADS clean javadoc:jar source:jar site -Dmaven.javadoc.failOnError=false -Dquiet=true

deploy:
  - mvn -B -T $MAVEN_THREADS org.sonatype.plugins:nexus-staging-maven-plugin:deploy -DnexusUrl=https://oss.sonatype.org/content/repositories/snapshots -DserverId=oss-snapshots -DreleaseType=snapshot

after_success:
  - bash ./trigger-dependent-build
